### ISSUE TITLE
Eigen lookAt Question

### ISSUE THREAD

**Issue by SaigeGithub** [luckysama/icg#11]
Hi, I saw this line "mat4 VIEW = Eigen::lookAt( vec3(1,1,1), vec3(0,0,0), vec3(0,1,0) );" in the main.cpp of the "lecture_viewing3d_fov_eigen", But I couldn't find any references.
Could you tell me,where is the Eigen::lookAt defined.. and how could I use it?

**Comment by taiya** [comment]
If you open the **icg_common.h** you see there is an EigenOpenGL.h include therein. The file is in the external OpenGP/OpenGL folder. Note that in qtcreator if you "CTRL+click" and include file you can open it!
