### ISSUE TITLE
glew and glfw dependencies in windows.

### ISSUE THREAD

**Issue by ShovelHand** [luckysama/icg#4]
The CMakeLists.txt files for compiling on windows point to the glew and glfw libraries being common/external, but they aren't actually there. I think I got the glew library working, but can't quite figure out how to get the glfw library working. Do you have any advice or directions on how to get these libraries in for my project?

**Comment by taiya** [comment]
Right, in the lab they are preinstalled.
I've just pushed them to the repo (for windows)
