### ISSUE TITLE
Library conflict on Windows 8 with QT and glew

### ISSUE THREAD

**Issue by SaigeGithub** [luckysama/icg#6]
Hi, I have a library conflict on windows 8 with QT and the given GLEW library. I have installed the correct version of visual studio community 2013.

If I download the zip file from the Github and compile it as-is, the compiler complains that there are methods being defined twice in some libraries:

```
[ 12%] Linking CXX executable D:\csc305\sdfds\icg-master\helloglsl\helloglsl.exe
MSVCRT.lib(MSVCR120.dll) : error LNK2005: _free already defined in LIBCMTD.lib(dbgfree.obj)

MSVCRT.lib(MSVCR120.dll) : error LNK2005: _strchr already defined in LIBCMTD.lib(strchr.obj)

MSVCRT.lib(MSVCR120.dll) : error LNK2005: _malloc already defined in LIBCMTD.lib(dbgmalloc.obj)

MSVCRT.lib(MSVCR120.dll) : error LNK2005: ___iob_func already defined in LIBCMTD.lib(_file.obj)

MSVCRT.lib(MSVCR120.dll) : error LNK2005: _fprintf already defined in LIBCMTD.lib(fprintf.obj)

(the list goes on and on...)
```

However, if I let the compiler not using these default libraries, then the compiler complains about cannot find certain things:

cmake:
set(CMAKE_EXE_LINKER_FLAGS
      "${CMAKE_EXE_LINKER_FLAGS} /NODEFAULTLIB")

compiler output:

```
[ 12%] Linking CXX executable D:\csc305\sdfds\icg-master\helloglsl\helloglsl.exe
main.cpp.obj : error LNK2001: unresolved external symbol __purecall

main.cpp.obj : error LNK2019: unresolved external symbol "void * __cdecl operator new(unsigned int)" (??2@YAPAXI@Z) referenced in function "char * __cdecl std::_Allocate<char>(unsigned int,char *)" (??$_Allocate@D@std@@YAPADIPAD@Z)

main.cpp.obj : error LNK2019: unresolved external symbol "void __cdecl operator delete(void *)" (??3@YAXPAX@Z) referenced in function "public: virtual void * __thiscall std::basic_filebuf<char,struct std::char_traits<char> >::`scalar deleting destructor'(unsigned int)" (??_G?$basic_filebuf@DU?$char_traits@D@std@@@std@@UAEPAXI@Z)

main.cpp.obj : error LNK2019: unresolved external symbol _atexit referenced in function "void __cdecl `dynamic initializer for 'public: static class std::_Generic_error_category std::_Error_objects<int>::_Generic_object''(void)" (??__E?_Generic_object@?$_Error_objects@H@std@@2V_Generic_error_category@2@A@@YAXXZ)

GLFW.lib(win32_init.obj) : error LNK2001: unresolved external symbol _atexit
```

**Comment by luckysama** [comment]
This is probably caused by GLFW 2 which is compiled in an older MSVC version than community 2013.
It may be solved by recompile GLFW 2's source code against MSVC 2013.
We're working on it.

**Comment by luckysama** [comment]
https://msdn.microsoft.com/en-us/library/aa267384(v=vs.60).aspx

According to MSDN, this might be caused by conflict in between default libraries. Since our CMAKE profile uses code generation option /MTd, we should ignore everything except of LIBCMTD.lib when compiling debugging version of code.

Adding the following file names into visual studio's project property page narrows the problem:

In Linker->Input->Ignore Specific Default Libraries, add:
![Linker Options](https://cloud.githubusercontent.com/assets/7647706/10556317/dc4d8732-7434-11e5-9de9-945adac436a8.png)

This narrows the problem down to one unresolved external symbol:

1>GLFW.lib(glext.obj) : error LNK2019: unresolved external symbol __imp__strstr referenced in function __glfwStringInExtensionString

I'm still tracking down this last one.

**Comment by sg16nop** [comment]
try getting rid of opencv in cmakelist. I suspect that the opencv lib and the GLFW lib are compiled using different runtime library. It worked for me.
p.s. I use Visual Studio

**Comment by luckysama** [comment]
I was able to run a few examples after disable the OpenCV reference in cmake list, but it is more than that. I'll make a check list below, at least on my humble laptop with only an Intel on-board graphics card, this was enough to get things working. (I hope all of you have better computer than mine)
- Recompile the GLFW 2.7.9 source code against VS12 (Visual Studio 2013) and use the newly compiled GLFW:
  http://sourceforge.net/projects/glfw/files/glfw/2.7.9/
- Disable openCV in the main CMakeList.txt. e.g. put a # in front of the line:
  include(common/OpenCV.cmake)
- Do as my previous post. Get rid of all unnecessary default libraries, only use LIBCMTD for debuging and LIBCMT for release version.
- Get rid of all GLEW hint requirement for openGL 3.2. Comment the following lines in the demo code. This is impossible for a Intel laptop video card.

``` cpp
    /// Hint GLFW that we would like an OpenGL 3 context (at least)
    /// http://www.glfw.org/faq.html#41__how_do_i_create_an_opengl_30_context
    //glfwOpenWindowHint(GLFW_OPENGL_VERSION_MAJOR, 3);
    //glfwOpenWindowHint(GLFW_OPENGL_VERSION_MINOR, 2);
    //glfwOpenWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);`    
```
- Make sure GLFW and GLEW are properly initialized. The "helloglsl" example gives correct example of how to initialize these two libraries:

``` cpp
/// GLFW Initialization
    if( !glfwInit() ){
        fprintf( stderr, "Failed to initialize GLFW\n" );
        return EXIT_FAILURE;
    }

    if( !glfwOpenWindow(512, 512, 0,0,0,0, 32,0, GLFW_WINDOW ) ){
        fprintf( stderr, "Failed to open OpenGL 3.2 GLFW window.\n" );
        glfwTerminate();
        return EXIT_FAILURE;
    }

    /// GLEW Initialization (must have a context)
    glewExperimental = true; ///< 
    if( glewInit() != GLEW_NO_ERROR ){
        fprintf( stderr, "Failed to initialize GLEW\n"); 
        return EXIT_FAILURE;
    }

    /// Set window title
    glfwSetWindowTitle("helloglsl");
```

Note that GLEW requires an openGL context to initialize, so do it after the call _"glfwOpenWindow()"_.

The following code segment, which also can be seen in many example projects, **doesn't work on Windows with Visual Studio**. Don't write like this. They seem to be fine on the Mac family computers, at least in the lab:

``` cpp
    //Code doesn't work on windows
    glfwInitWindowSize(512, 512);
    glfwCreateWindow("planets");
    glfwDisplayFunc(display);
    init();
    glfwMainLoop();
```

These codes don't explicit initialize GLEW, and cause GLEW's function pointer searcher (_GLEW_GET_FUN_) to fail and return a NULL pointer.
- The last point is not directly related to this issue but I'll mention it here: Check your working directory, and make sure that from that directory, the shader files could be loaded. CMAKE sets weired paths for the working directory which usually isn't the path contain the shader files. Either manually edit that directory or copy your shader files into the working directory set by CMAKE.

![working directory](https://cloud.githubusercontent.com/assets/7647706/10569326/6aa90ad8-75d9-11e5-86aa-7c7ae44797b9.jpg)

**Comment by SaigeGithub** [comment]
I might go to your office hour to talk about it, thanks a lot Lucky
