### ISSUE TITLE
opengp::glfwTrackball Potential ODR Violation

### ISSUE THREAD

**Issue by RobertLeahy** [luckysama/icg#7]
The function opengp::glfwTrackball is declared in external/OpenGP/GL/glfw_trackball.h file, however it is not marked inline and therefore has external linkage (functions have external linkage by default).
As it is in a header it may be included in multiple translation units.  The compiler will dutifully emit its code into each resulting object file, which will then cause a linker error.
To rectify this opengp::glfwTrackball should be marked inline.  This will give it internal linkage and cause the linker to cull any duplicates found.

**Comment by taiya** [comment]
Can you send in a pull request?
